### ISSUE TITLE
[Bug]  破坏原生ui的 script 下拉列表

### ISSUE THREAD

**Issue by xueque** [lobehub/sd-webui-lobe-theme#399]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

e5ff6bd3bcb34a68cec7fd9d75f1e8dc1ad2f91a

### 📦 Lobe Theme 版本或提交 | Version or Commit

v3.0.4

### 🐛 问题描述 | Bug Description

破坏了 #txt2img_script_container 的样式
![QQ图片20230909033803](https://github.com/lobehub/sd-webui-lobe-theme/assets/52696197/bf0cb88a-b930-43e5-a179-2b2b25109a98)
![QQ图片20230909033856](https://github.com/lobehub/sd-webui-lobe-theme/assets/52696197/0a4b3fa4-9db6-44ec-8128-aaa41d633238)
关闭这个 ui 扩展模块后,  #txt2img_script_container 会恢复正常.

### 🚦 期望结果 | Expected Behavior

修复与 #txt2img_script_container 的样式冲突

### 📝 补充信息 | Additional Information

我的临时解决方案
stable-diffusion-webui/style.css
```css
#txt2img_settings{
    flex-grow: 2!important;
}
#txt2img_script_container{
    display: none !important; 
}
```
