### ISSUE TITLE
[Bug] Mobile UI - module image preview

### ISSUE THREAD

**Issue by M3g4m3** [lobehub/sd-webui-lobe-theme#421]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The image preview cluster is not fixed but overlaps other UIs when scrolling the page

**Comment by KingPungy** [comment]
please fix this. the mobile app is not usable like this. 
The moment you generate an image the generation parameters overlap with all the settings and flow off screen.

This seems to be the problem for the image container that overlaps everything.
To remove overlapping:
```css
div.gradio-container, .block.gradio-textbox, div.gradio-group, div.gradio-dropdown {
    overflow: visible !important;   " <- this needs to be gone or disabled"
}
```

for this element:
```html
<div id="txt2img_gallery_container"   ...
```

To center the generation parameters on the screen:
add: 
width: 100%
to style like below
```html
<div id="txt2img_results" class="gradio-column svelte-vt1mxs gap panel mobile" style="flex-grow: 1;width: 100%;">
```
